version: 1.0.{build}
image: Visual Studio 2013
platform:
- x86
- x64
build:
  verbosity: minimal
artifacts:
- path: bin
  name: '%APPVEYOR_PROJECT_NAME% v%APPVEYOR_BUILD_VERSION%_%PLATFORM%'
