version: 1.0.{build}
image: Visual Studio 2013
platform:
- x86
- x64
build:
  verbosity: minimal
artifacts:
- path: LabelPEB
  name: '%APPVEYOR_PROJECT_NAME% %APPVEYOR_REPO_BRANCH% %APPVEYOR_BUILD_VERSION%_binaries'
