version: 1.0.{build}
image: Visual Studio 2013
platform:
- x86
- x64
build:
  verbosity: minimal
artifacts:
- path: labelpeb\bin\
  name: '%APPVEYOR_PROJECT_NAME% %APPVEYOR_REPO_BRANCH% %APPVEYOR_BUILD_NUMBER%.%APPVEYOR_BUILD_VERSION%_binaries'
